<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>edu.umg.programacion2</groupId>
    <artifactId>libreria-catalogo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <!--
        POM "padre". No compila nada por si mismo (packaging=pom), solo
        agrupa los modulos hijos y centraliza propiedades/version comunes
        para que no queden duplicadas en cada modulo.
    -->
    <modules>
        <module>libreria-catalogo-core</module>
        <module>libreria-catalogo-ui</module>
    </modules>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mysql.connector.version>8.3.0</mysql.connector.version>
    </properties>

</project>
