<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>edu.umg.programacion2</groupId>
        <artifactId>libreria-catalogo</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <!--
        Modulo "libreria" (jar). Aqui vive el modelo (Libro) y el DAO
        (LibroDAO) con todo el JDBC. NO tiene ninguna dependencia de Swing:
        si algo aqui intentara importar javax.swing.*, compilaria igual
        (Swing es parte del JDK), pero la idea es que conceptualmente este
        modulo no sepa que existe una interfaz grafica -- solo sabe hablar
        con la base de datos.
    -->
    <artifactId>libreria-catalogo-core</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>${mysql.connector.version}</version>
        </dependency>
    </dependencies>

</project>
